ImageMarkup/isic

isic/conftest.py
isic/core/models/collection.py
isic/core/permissions.py
isic/core/stats.py
isic/core/tests/factories.py
isic/core/tests/test_permissions.py
isic/core/urls.py
isic/core/views.py
isic/ingest/models/cohort.py
isic/ingest/models/contributor.py
isic/ingest/models/metadata_file.py
isic/ingest/tests/test_permissions.py
isic/ingest/urls.py
isic/ingest/utils/__init__.py
isic/ingest/views/__init__.py
isic/ingest/views/metadata.py
isic/ingest/views/upload.py
isic/settings.py
isic/studies/tests/test_permissions.py
isic/urls.py

This adds a VERY WIP version of permissions.

Add preliminary permissions module

---

isic/login/backends.py
isic/login/tests/test_backends.py
setup.py

Also, use the same hashing implementation (with passlib) as upstream Girder.

Implement Girder password encoding

---

isic/core/management/commands/fix-girder-images.py

- Fix user count for statistics
- Update fix-girder-images to process accessions

fix girder image script

---

isic/ingest/templates/ingest/partials/review_footer.html
isic/ingest/urls.py
isic/ingest/views/review_apps.py

This helped me catch a bug that will lead to a 10x performance boost on the lesion review app.

Rewrite lesion review app as FBV

---

isic/core/templates/core/partials/image.html
isic/core/templates/core/partials/image_modal.html
isic/ingest/templates/ingest/partials/accession.html
isic/ingest/templates/ingest/partials/accession_modal.html

Only load thumbnails on page load, and eagerly load full size
images on thumbnail hover.

Improve browser load times

---

isic/core/templates/core/partials/image_modal.html
isic/studies/templates/studies/study_detail.html
isic/studies/templates/studies/study_task_detail.html

This is a bit messy with `width: inherit` splattered everywhere, but I think it's a good solution for the image and questions columns. Let me know what you think @danlamanna 
For clarification, the `width: inherit` is needed for fixed position elements to inherit the width of the parent.

Implement fix for question and image columns

---

isic/settings.py

This reverts commit e34ef0bd7be4d98b263c3ae737c89e52dda6e627.

Revert "Revert "Temporarily revert cloudfront""

---

isic/settings.py

This reverts commit b7639b73d13ec3ec54018fac868abc63b528528c.

Revert "Revert "Revert "Temporarily revert cloudfront"""

---

isic/core/search.py
isic/core/utils/logging.py

Fix logger silencing code

---

isic/ingest/api.py

This endpoint currently does `2*len(checks)*len(accessions)` writes, which for lesion review page can easily be 300-800 per request. Using bulk operations has a lot of drawbacks though so I'm just leaving this as a draft.

Improve performance of accession review endpoint

---

isic/core/templates/core/base.html

- Add remove_metadata method
- Fix duplicative code from merge conflict

fix merge conf

---

isic/ingest/management/commands/apply-metadata-files.py
isic/ingest/management/commands/metadata-files-from-csv.py
isic/ingest/models/accession.py
isic/ingest/tests/test_metadata.py

- Stop creating metadata revisions for empty updates
- Fix metadata apply script to exclude extraneous columns

Fix misc metadata application bugs

---

tox.ini

Revert "Remove a fixed upstream warning"

---

isic/stats/tasks.py
isic/stats/tests/test_tasks.py

- Fix cloudfront log parsing
- Improve memory consumption of download tracking

fix cf parsing

---

isic/ingest/admin.py

Computing these is too slow for now.

Remove additional information from cohort admin

---

isic/ingest/management/commands/revalidate-metadata.py
isic/ingest/models/accession.py
isic/ingest/utils/metadata.py
isic/ingest/views/upload.py
setup.py

related https://github.com/ImageMarkup/tracker/issues/135

Upgrade isic-metadata to support pydantic 2

---

isic/core/models/base.py
isic/core/templates/core/collection_detail.html
isic/core/views/collections.py
isic/ingest/models/cohort.py
isic/ingest/services/cohort/__init__.py
isic/ingest/tests/test_cohort.py

related https://github.com/ImageMarkup/tracker/issues/151

Add cohort relicensing

---

isic/stats/admin.py

related https://github.com/ImageMarkup/tracker/issues/150

Improve admin page speed for image download stats

---

isic/core/templates/core/base.html
isic/core/templates/core/partials/nav_elements.html
isic/settings.py

related https://github.com/ImageMarkup/tracker/issues/157

Canonicalize ISIC links

---

isic/core/pagination.py

This is one of two changes I want to make in order to upstream this. The other is to add translation to the text; I wasn't planning to do that in ISIC, but if you want me to, I can.

Validate cursor parameter in paginator

---

isic/core/admin.py

Add:
* Filter by presence of DOI
* Creation date column
* Search by DOI
* Order by number of images

Enhance the Collection admin page

---

isic/ingest/admin.py

* Order "Created" before "Creator"
* Drop unnecessary "id" columns

Improve some admin columns

---

isic/core/dsl.py
isic/core/search.py
isic/core/tests/test_dsl.py
isic/core/tests/test_search.py

related https://github.com/ImageMarkup/tracker/issues/158

Add missing/present value counts to facet results

---

isic/settings.py
isic/zip_download/api.py
isic/zip_download/tests/test_zip_download.py

related https://github.com/ImageMarkup/tracker/issues/159

Add cloudfront signing optimization to zip-file-listing

---

isic/ingest/models/metadata_file.py

related https://github.com/ImageMarkup/tracker/issues/167

Strip metadata strings before processing

---

isic/ingest/models/metadata_file.py
setup.py

related https://github.com/ImageMarkup/tracker/issues/167

Offload empty metadata row processing to isic-metadata

---

isic/ingest/templates/ingest/review_gallery.html
isic/ingest/views/review.py

related https://github.com/ImageMarkup/tracker/issues/163

Sort cohort review by filename

---

isic/core/services/__init__.py
isic/ingest/templates/ingest/partials/cohort_list_actions.html
isic/ingest/tests/test_cohort.py
isic/ingest/tests/test_permissions.py
isic/ingest/urls.py
isic/ingest/views/cohort.py

related https://github.com/ImageMarkup/tracker/issues/165

Add the ability to download all accession metadata

---

isic/core/services/__init__.py
isic/core/templates/core/image_list_export.html
isic/core/templates/core/partials/nav_elements.html
isic/core/tests/test_permissions.py
isic/core/tests/test_view_image_list.py
isic/core/urls.py
isic/core/views/images.py
isic/ingest/templates/ingest/partials/cohort_list_actions.html
isic/ingest/tests/factories.py
isic/ingest/tests/test_cohort.py
isic/ingest/tests/test_permissions.py
isic/ingest/urls.py
isic/ingest/views/cohort.py

related https://github.com/ImageMarkup/tracker/issues/165

Make full metadata csv use published images only

---

isic/celery.py
isic/core/apps.py

Revert "Add sentry cron monitoring"

---

isic/conftest.py
isic/core/models/image.py
isic/ingest/api.py
isic/ingest/models/lesion.py
isic/ingest/tests/factories.py
isic/ingest/tests/test_api_lesion.py
isic/urls.py

related https://github.com/ImageMarkup/tracker/issues/161

Add lesion listing endpoint

---

isic/core/pagination.py
isic/ingest/api.py
isic/ingest/models/lesion.py
isic/ingest/tests/test_api_lesion.py

related https://github.com/ImageMarkup/tracker/issues/161

Improve lesion endpoint count performance

---

isic/ingest/api.py
isic/ingest/models/lesion.py
isic/ingest/tests/test_api_lesion.py

related https://github.com/ImageMarkup/tracker/issues/161

Add additional computed fields to the lesion endpoint

---

isic/core/search.py

related https://github.com/ImageMarkup/tracker/issues/176

Add default fitzpatrick_skin_type values to facet counts

---

isic/core/search.py
isic/core/tests/test_search.py

related github.com/ImageMarkup/tracker/issues/183

Ensure facet value population and sorting

---

isic/ingest/models/metadata_file.py
isic/ingest/tasks.py
isic/ingest/tests/conftest.py
isic/ingest/tests/csv_streams.py
isic/ingest/tests/test_metadata.py
isic/ingest/utils/metadata.py

Revert "Add support for utf-8-sig encoded CSVs"

---

isic/core/services/collection/__init__.py
isic/core/services/collection/image.py
isic/core/tests/test_collection_shares.py

related github.com/ImageMarkup/tracker/issues/186

Add service API for sharing collections

---

isic/core/api/collection.py
isic/core/models/collection.py
isic/core/services/collection/__init__.py
isic/core/tasks.py
isic/core/templates/core/collection_detail.html
isic/core/templates/core/partials/collection_detail_actions.html
isic/core/templates/core/partials/collection_share_modal.html
isic/core/tests/test_api_collection.py
isic/core/tests/test_api_permissions.py
isic/core/views/collections.py
isic/ingest/api.py
node-src/styles.pcss

related https://github.com/ImageMarkup/tracker/issues/186

Add share dialog for collection detail page

---

isic/core/services/collection/__init__.py
isic/core/templates/core/partials/collection_detail_actions.html
isic/core/views/collections.py
setup.py

related https://github.com/ImageMarkup/tracker/issues/186

Disable sharing for public collections

---

isic/core/admin.py
isic/core/tests/test_api_collection.py
isic/find/api.py
isic/ingest/api.py
isic/ingest/forms.py
isic/ingest/services/cohort/__init__.py
isic/ingest/tasks.py
isic/ingest/templates/ingest/cohort_publish.html
isic/ingest/tests/test_permissions.py
isic/ingest/tests/test_publish.py
isic/ingest/views/cohort.py
isic/urls.py
node-src/styles.pcss

related https://github.com/ImageMarkup/tracker/issues/185

Add support for publishing a cohort to additional collections

---

isic/core/templates/core/collection_detail.html
isic/core/views/collections.py

related https://github.com/ImageMarkup/tracker/issues/186

Improve shares display

---

isic/core/api/collection.py
isic/core/tests/test_api_collection.py

related https://github.com/ImageMarkup/tracker/issues/189

Add an endpoint for finding a collection by name

---

isic/core/templates/core/image_detail/base.html
isic/core/templates/core/partials/image_modal.html
isic/ingest/templates/ingest/accession_cog_viewer.html
node-src/cog.mjs

This now reads the extent from the image itself.

Simplify the COG viewer code

---

isic/core/search.py
isic/core/tasks.py
isic/core/tests/test_search.py

This offers similar functionality to cachalot but for our elasticsearch queries.

Add general elasticsearch query caching

---

isic/middleware.py
isic/settings/base.py
isic/urls.py

Revert "Allow Ninja to enforce CSRF on a per-auth method basis"

---

isic/factories.py
isic/login/models.py
isic/login/tests/test_hashers.py
pyproject.toml
uv.lock

See also https://github.com/ImageMarkup/isic/pull/1292.

Remove usage of the hashids library

---

isic/core/tasks.py

Revert "Add temporary task for embedding IPTC metadata"

---

isic/core/tasks.py

This reverts commit 463f962e852f9ba91fb15fda7cc20851e6321fc7.

Revert "Add temporary task for generating sponsored blobs"

---

isic/settings/base.py

Revert "Temporarily disable redis cache"

---

isic/core/templates/core/collection_detail.html
isic/core/templates/core/collection_list.html
isic/core/templates/core/image_browser.html
isic/settings/base.py
pyproject.toml
uv.lock

[django-template-partials](https://github.com/carltongibson/django-template-partials) is being added to core django in 6.0. I decided to implement it here ahead of time to see what it looks like.
After adding it to a few places where it made sense, it didn't clean things up as much as I'd hoped, but I'm still probably going to merge it.

Add django-template-partials
